### ISSUE TITLE
What distro is the rootfs based on -or- is there a choice?

### ISSUE THREAD

**Issue by bmullan** [Jayfrown/container-overlay#1]
I was curious if container-overlay provides the user a choice of what linux distro the rootfs is?

thanks
brian

**Comment by Jayfrown** [comment]
Hadn't noticed this comment until now - sorry for the extremely late reply.
For anyone still interested, the idea is indeed for there to be a choice of base distro.

Currently, for the bash scripts under this repo, it's configurable under [cor.cfg:40](https://github.com/Jayfrown/container-overlay/blob/master/cor.cfg#L40) -- by default set to `images:archlinux`. It can be any `remote:image` pair known by your LXD instance.

I would add command-line support to configure this option, but I've set out to rewrite the container/overlay concept in python. I'm toying with the idea of having multiple base containers, or allowing any user-made container to be the base (selecting it on command-line). We'll see where that ends up. Current work-in-progress can be tracked at the [pycor-cli repo](https://github.com/Jayfrown/pycor-cli).
